### ISSUE TITLE
use `starting` exit code for health check while service hasn't started listening

### ISSUE THREAD

**Issue by dr-bonez** [Start9Labs/ride-the-lightning-wrapper#12]
currently when you start RTL, it shows a health check error until things have time to start up. this is a bad experience for the user as they will think something is broken when it isn't.

**Comment by chrisguida** [comment]
Fixed by d63742e53a108a62d925b57d295672ee950a486e

**Comment by dr-bonez** [comment]
not a fan of this solution. This does not account for something actually wrong with the service, it will always indicate "starting" even an hour after it starts, which would be a symptom of a problem. @elvece can advise on the correct solution

**Comment by elvece** [comment]
[Here](https://github.com/Start9Labs/btcpayserver-wrapper/blob/integration/1.1.2.4/assets/utils/health_check.sh#L44) is how I implemented this for btcpay.

**Comment by chrisguida** [comment]
Better? 52ff0d4c2bca10bdcf107b35093759e65507d18d

**Comment by chrisguida** [comment]
Actually now i'm getting this:

<img width="1188" alt="Screen Shot 2022-01-26 at 5 45 01 PM" src="https://user-images.githubusercontent.com/7445670/151270077-46e2b4de-c243-48d1-af5b-cbaf56ce1698.png">

Any idea what I did wrong?

**Comment by dr-bonez** [comment]
this is bash, not sh. change your shebang to `/bin/bash`

**Comment by chrisguida** [comment]
Ah, I suspected that, thanks. Adding `bash` to the container.

**Comment by chrisguida** [comment]
Fixed 2da269c00f79e6d0e07fc57011811f9a31a93941

**Comment by chrisguida** [comment]
Ok, now it's just stuck on starting. Any idea what the problem might be now? @dr-bonez @elvece 

<img width="507" alt="Screen Shot 2022-01-27 at 12 32 50 PM" src="https://user-images.githubusercontent.com/7445670/151421893-03133ec5-42ab-4c04-9cb4-4a5d0949257e.png">

**Comment by ProofOfKeags** [comment]
what do the logs say?

**Comment by elvece** [comment]
it will say "Starting" for 30 seconds with the code implemented. Also, the response that is being captured is the exit code. Is it persisting "Starting" for longer than that? Try out the `curl` command and see if its accurate for RTL, there might be slight differences from service to service.

**Comment by chrisguida** [comment]
Definitely longer than 30 seconds. I had 18 hours of uptime.

**Comment by chrisguida** [comment]
@ProofOfKeags nothing out of the ordinary

<img width="1100" alt="Screen Shot 2022-01-27 at 12 37 58 PM" src="https://user-images.githubusercontent.com/7445670/151422810-5ce161d9-e0a9-4807-b7de-f95a2bd9f7f9.png">

**Comment by chrisguida** [comment]
@elvece curl command works fine

```
# docker exec -it ride-the-lightning.embassy curl --silent --show-error --fail ride-the-lightning.embassy:80
<!DOCTYPE html><html lang="en"><head>
  <meta charset="utf-8">
  <title>RTL</title>
  <base href="/rtl/">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="apple-touch-icon" sizes="180x180" href="assets/images/favicon-light/apple-touch-icon.png">
  <link rel="icon" type="image/png" sizes="32x32" href="assets/images/favicon-light/favicon-32x32.png">
  <link rel="icon" type="image/png" sizes="16x16" href="assets/images/favicon-light/favicon-16x16.png">
  <link rel="manifest" href="assets/images/favicon-light/site.webmanifest">
  <link rel="mask-icon" href="assets/images/favicon-light/safari-pinned-tab.svg" color="#5bbad5">
  <meta name="msapplication-TileColor" content="#da532c">
  <meta name="theme-color" content="#ffffff">
<style>@font-face{font-family:Roboto;src:url(Roboto-Thin.dbd56bd3357dc3617fe5.woff2) format("woff2"),url(Roboto-Thin.e7f7c82374bd0ebef14b.woff) format("woff");font-weight:100;font-style:normal;}@font-face{font-family:Roboto;src:url(Roboto-ThinItalic.a8cef84f735ef887abdc.woff2) format("woff2"),url(Roboto-ThinItalic.5dd9349c940073834e9a.woff) format("woff");font-weight:100;font-style:italic;}@font-face{font-family:Roboto;src:url(Roboto-Light.c27d89ac77468ae18f28.woff2) format("woff2"),url(Roboto-Light.d923dfafc0c5183b59aa.woff) format("woff");font-weight:300;font-style:normal;}@font-face{font-family:Roboto;src:url(Roboto-LightItalic.506274c7228cf81cae4d.woff2) format("woff2"),url(Roboto-LightItalic.d4b8c137518d9d92bb28.woff) format("woff");font-weight:300;font-style:italic;}@font-face{font-family:Roboto;src:url(Roboto-Regular.64cfb66c866ea50cad47.woff2) format("woff2"),url(Roboto-Regular.e02e9d6ff5547f7e9962.woff) format("woff");font-weight:400;font-style:normal;}@font-face{font-family:Roboto;src:url(Roboto-RegularItalic.4dd2af1e8df532f41db8.woff2) format("woff2"),url(Roboto-RegularItalic.5ea38fff9eebef99c5df.woff) format("woff");font-weight:400;font-style:italic;}@font-face{font-family:Roboto;src:url(Roboto-Medium.1d3bced88509b0838984.woff2) format("woff2"),url(Roboto-Medium.092c6130df8fd2199888.woff) format("woff");font-weight:500;font-style:normal;}@font-face{font-family:Roboto;src:url(Roboto-MediumItalic.d620b8f53f75966fe42e.woff2) format("woff2"),url(Roboto-MediumItalic.18ff1628c628080166c1.woff) format("woff");font-weight:500;font-style:italic;}@font-face{font-family:Roboto;src:url(Roboto-Bold.92fbd4e93cf0a5dbebaa.woff2) format("woff2"),url(Roboto-Bold.73288d91c325e82a5b92.woff) format("woff");font-weight:700;font-style:normal;}@font-face{font-family:Roboto;src:url(Roboto-BoldItalic.5f600d98a73d800ae575.woff2) format("woff2"),url(Roboto-BoldItalic.6d89acbd21d7e3fbecb2.woff) format("woff");font-weight:700;font-style:italic;}@font-face{font-family:Roboto;src:url(Roboto-Black.41ed1105a6ebb8ffe34e.woff2) format("woff2"),url(Roboto-Black.937491dfcbe64ca9a9f1.woff) format("woff");font-weight:900;font-style:normal;}@font-face{font-family:Roboto;src:url(Roboto-BlackItalic.50ca4c51ebc27e7e7d2f.woff2) format("woff2"),url(Roboto-BlackItalic.2e1ee657996854c6f427.woff) format("woff");font-weight:900;font-style:italic;}html{width:100%;height:99%;line-height:1.5;overflow-x:hidden;font-family:Roboto,sans-serif!important;font-size:62.5%;}body{box-sizing:border-box;margin:0;}body{height:100%;overflow:hidden;}*{margin:0;padding:0;}</style><link rel="stylesheet" href="styles.97554e699a42acff6579.css" media="print" onload="this.media='all'"><noscript><link rel="stylesheet" href="styles.97554e699a42acff6579.css"></noscript></head>
<body>
  <rtl-app></rtl-app>
<script src="runtime.28bc9723e141277838d0.js" defer></script><script src="polyfills.99f4d82f067fba7525c4.js" defer></script><script src="main.0fde3abb5a45cd8835db.js" defer></script>
```

**Comment by chrisguida** [comment]
seems to work fine if i manually feed it 30001 on stdin too:

```
bash-5.0# check-web.sh
30001
<!DOCTYPE html><html lang="en"><head>
  <meta charset="utf-8">
  <title>RTL</title>
  <base href="/rtl/">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="apple-touch-icon" sizes="180x180" href="assets/images/favicon-light/apple-touch-icon.png">
  <link rel="icon" type="image/png" sizes="32x32" href="assets/images/favicon-light/favicon-32x32.png">
  <link rel="icon" type="image/png" sizes="16x16" href="assets/images/favicon-light/favicon-16x16.png">
  <link rel="manifest" href="assets/images/favicon-light/site.webmanifest">
  <link rel="mask-icon" href="assets/images/favicon-light/safari-pinned-tab.svg" color="#5bbad5">
  <meta name="msapplication-TileColor" content="#da532c">
  <meta name="theme-color" content="#ffffff">
<style>@font-face{font-family:Roboto;src:url(Roboto-Thin.dbd56bd3357dc3617fe5.woff2) format("woff2"),url(Roboto-Thin.e7f7c82374bd0ebef14b.woff) format("woff");font-weight:100;font-style:normal;}@font-face{font-family:Roboto;src:url(Roboto-ThinItalic.a8cef84f735ef887abdc.woff2) format("woff2"),url(Roboto-ThinItalic.5dd9349c940073834e9a.woff) format("woff");font-weight:100;font-style:italic;}@font-face{font-family:Roboto;src:url(Roboto-Light.c27d89ac77468ae18f28.woff2) format("woff2"),url(Roboto-Light.d923dfafc0c5183b59aa.woff) format("woff");font-weight:300;font-style:normal;}@font-face{font-family:Roboto;src:url(Roboto-LightItalic.506274c7228cf81cae4d.woff2) format("woff2"),url(Roboto-LightItalic.d4b8c137518d9d92bb28.woff) format("woff");font-weight:300;font-style:italic;}@font-face{font-family:Roboto;src:url(Roboto-Regular.64cfb66c866ea50cad47.woff2) format("woff2"),url(Roboto-Regular.e02e9d6ff5547f7e9962.woff) format("woff");font-weight:400;font-style:normal;}@font-face{font-family:Roboto;src:url(Roboto-RegularItalic.4dd2af1e8df532f41db8.woff2) format("woff2"),url(Roboto-RegularItalic.5ea38fff9eebef99c5df.woff) format("woff");font-weight:400;font-style:italic;}@font-face{font-family:Roboto;src:url(Roboto-Medium.1d3bced88509b0838984.woff2) format("woff2"),url(Roboto-Medium.092c6130df8fd2199888.woff) format("woff");font-weight:500;font-style:normal;}@font-face{font-family:Roboto;src:url(Roboto-MediumItalic.d620b8f53f75966fe42e.woff2) format("woff2"),url(Roboto-MediumItalic.18ff1628c628080166c1.woff) format("woff");font-weight:500;font-style:italic;}@font-face{font-family:Roboto;src:url(Roboto-Bold.92fbd4e93cf0a5dbebaa.woff2) format("woff2"),url(Roboto-Bold.73288d91c325e82a5b92.woff) format("woff");font-weight:700;font-style:normal;}@font-face{font-family:Roboto;src:url(Roboto-BoldItalic.5f600d98a73d800ae575.woff2) format("woff2"),url(Roboto-BoldItalic.6d89acbd21d7e3fbecb2.woff) format("woff");font-weight:700;font-style:italic;}@font-face{font-family:Roboto;src:url(Roboto-Black.41ed1105a6ebb8ffe34e.woff2) format("woff2"),url(Roboto-Black.937491dfcbe64ca9a9f1.woff) format("woff");font-weight:900;font-style:normal;}@font-face{font-family:Roboto;src:url(Roboto-BlackItalic.50ca4c51ebc27e7e7d2f.woff2) format("woff2"),url(Roboto-BlackItalic.2e1ee657996854c6f427.woff) format("woff");font-weight:900;font-style:italic;}html{width:100%;height:99%;line-height:1.5;overflow-x:hidden;font-family:Roboto,sans-serif!important;font-size:62.5%;}body{box-sizing:border-box;margin:0;}body{height:100%;overflow:hidden;}*{margin:0;padding:0;}</style><link rel="stylesheet" href="styles.97554e699a42acff6579.css" media="print" onload="this.media='all'"><noscript><link rel="stylesheet" href="styles.97554e699a42acff6579.css"></noscript></head>
<body>
  <rtl-app></rtl-app>
<script src="runtime.28bc9723e141277838d0.js" defer></script><script src="polyfills.99f4d82f067fba7525c4.js" defer></script><script src="main.0fde3abb5a45cd8835db.js" defer></script>

</body></html>bash-5.0# echo $?
0

```

**Comment by chrisguida** [comment]
29999 also gives the expected result

```
bash-5.0# check-web.sh
29999
bash-5.0# echo $?
60

```

**Comment by ProofOfKeags** [comment]
If you refresh the UI (ctrl+shift+R) does it correct? This may be an OS issue.

**Comment by chrisguida** [comment]
@ProofOfKeags hard refresh has no effect

**Comment by ProofOfKeags** [comment]
OK I'm interested then in what the embassyd logs are wrt health checks, if you could see what that is. I have a feeling this isn't an intrinsic issue with RTL. Are any other services having misbehaving healthchecks where they get stuck. My read of the above comments is that the actual health check script seems to work fine. This probably means that the state isn't getting committed to patchdb properly.

**Comment by chrisguida** [comment]
I'm thinking the stdin part isn't working the way it's supposed to

**Comment by chrisguida** [comment]
@ProofOfKeags there don't seem to be any logs. This health check is `docker exec` so I'd expect the logs to show up in the container

**Comment by elvece** [comment]
I don't yet know why, but `io-format: json` in the manifest fixes this

**Comment by dr-bonez** [comment]
Yeah if you don't have an io-format the container won't receive input over stdin

**Comment by ProofOfKeags** [comment]
Does the format define how the stdin is formatted?

**Comment by elvece** [comment]
> Yeah if you don't have an io-format the container won't receive input over stdin

No, there was always an `io-format` specified. It's failing when `io-format: yaml`, but not when its `json`, or `toml`.

**Comment by ProofOfKeags** [comment]
> Does the format define how the stdin is formatted?

^ this seems important. iirc your bash loop is predicated on being able to parse numbers. If the format of the container uptime changes depending on your ioformat then you may be doing a string comparison which always yields true causing you to always exit 60

**Comment by dr-bonez** [comment]
> > Yeah if you don't have an io-format the container won't receive input over stdin
> 
> No, there was always an `io-format` specified. It's failing when `io-format: yaml`, but not when its `json`, or `toml`.

`yaml` will give you 3 dashes on a separate line before the number. `toml` I'm not sure how raw numbers are formatted

**Comment by ProofOfKeags** [comment]
> yaml will give you 3 dashes on a separate line before the number. toml I'm not sure how raw numbers are formatted

my money is on this being the issue. toml + json have raw numbers, yaml has 3 dashes as a document separator, which causes the variable to be interpreted as a string, and strings are lexicographically compared in bash. This will force the bash script to always choose one arm instead of the other.

**Comment by elvece** [comment]
Ok that could be the issue with yaml, weird that it does that.

This is how I'm comparing the input, afaik the `()` coerce to number comparison in bash, but could be incorrect:

```
    DURATION=$(</dev/stdin)
    if (($DURATION <= 30000 )); then 
        exit 60
    else
...
```

edit: maybe coerce isnt the right word - its meant for number comparison. I should probably parse the stdin as number always.

**Comment by ProofOfKeags** [comment]
> afaik the () coerce to number comparison in bash, but could be incorrect:

I mean yes but can it coerce this:
```yaml
---
300
```
into `300`

I'm somewhat doubtful.

**Comment by elvece** [comment]
It seems like the best solution then would be to pass in the ioformat as an argument to the health check and then use yq, jq, tq to parse it

**Comment by ProofOfKeags** [comment]
Why would you pass the argument in, isn't that what the ioformat of the manifest is supposed to denote?

**Comment by elvece** [comment]
the health check is a separate script and has no knowledge of that value. I could also read it from the manifest in that script, sure.

**Comment by ProofOfKeags** [comment]
But the ioformat is specified for the health check in the manifest. Since it is developer defined, why do you need it as an argument? By passing it as an argument you require the health check script to be able to tolerate all different ioformats, increasing code bloat. I think what you ought to do is just choose the format you feel like parsing, set that as the ioformat and then be on your merry way.

https://github.com/Start9Labs/ride-the-lightning-wrapper/blob/0.3.0/manifest.yaml#L30-L38

**Comment by elvece** [comment]
Yeah I'm dumb - I thought it would be best to have the health check handle any case, if, for some reason, the io-format was changed in the manifest, then it wouldnt fail. but if the developer is changing the manifest, its their responsibility to alter anything that would be affected downstream.

**Comment by ProofOfKeags** [comment]
Yeah I can see in the future a tool that extracts certain comments from health check scripts and uses that to autogenerate the manifest but we can work on DX stuff later. For now I think the best design is to not require health checks to handle all io-formats.

**Comment by elvece** [comment]
Cool - this is fixed [here](https://github.com/Start9Labs/ride-the-lightning-wrapper/pull/8/commits/7c71fe78920d2204f87ce45f431cd17adaf75667)

Deploying to beta now, it has already been tested, I think this ticket can be closed, or at least moved to UAT.

**Comment by chrisguida** [comment]
Tested, works
