### ISSUE TITLE
Genseed Generation Failed

### ISSUE THREAD

**Issue by wroscoe** [Start9Labs/ride-the-lightning-wrapper#2]
I have an embassy configured with all the default settings. 

When I try to Initialize a new wallet in RTL (`<my_onion_address>/rtl/lnd/wallet`) after I've entered a password, confirmed a cipher will be created, and not entered a passphrase I get  a pop up saying... 

```
Genseed Generation Failed
Error Code:500
API URL: ./api/lnd/wallet/genseed/
```

The LND service is active on my embassy. What could be going wrong here and how can I configure this to create a new wallet. Thanks.

**Comment by ProofOfKeags** [comment]
Your wallet should be created automatically from within LND. Is there a reason you are trying to do it from RTL?

**Comment by wroscoe** [comment]
Maybe a wallet was created. Where do I find that password for the automatically created wallet? When I go to RTL I'm prompted to enter my wallet password. When I enter random chars into the wallet password form I get the error:
```
Unlock Wallet Failed
Error Code
500
Error Message
404 - "Not Found\n"
API URL
./api/lnd/wallet/unlockwallet
```

**Comment by ProofOfKeags** [comment]
The password is stored in the LND volume. Is the Embassy LND package running *before* you start RTL?

**Comment by wroscoe** [comment]
I uninstalled and reinstalled RTL and now I'm not prompted for a password. Thank you. Maybe this dependency could be checked at RTL launch time or I could add some FAQ to the RTL install instructions. Thanks for your help.

**Comment by ProofOfKeags** [comment]
Did you try restarting RTL before uninstalling? Asking so I know whether or not to file a bug.

**Comment by wroscoe** [comment]
I didn't restart the RTL service individually but the Embassy Pi had recently been restarted.

**Comment by ProofOfKeags** [comment]
The 0.3.0 upgrade for embassy OS includes healthchecks. Once this is implemented we will upgrade the packages to use this feature and not indicate that lnd is ready until the wallet has been unlocked. This should remove the possibility of this happening to you.
