### ISSUE TITLE
[bug]: RTL password reset flow via the Services -> RTL -> Config -> Save is not effective

### ISSUE THREAD

**Issue by gStart9** [Start9Labs/ride-the-lightning-wrapper#26]
### Prerequisites

- [X] I have searched for existing issues that already report this problem.

### Device

Laptop/Desktop

### Device OS

Linux

### Device OS Version

0.13.1

### Browser

Firefox

### Browser Version

104

### Current Behavior

Attempting to change the user's RTL password via `Services -> RTL -> Config -> Save` *appears* to update, and in fact when you go view to confirm that you changed it in the embassy interface, the interface displays it as if it was successfully changed.

Yet, logging into RTL itself still requires the old password.

### Expected Behavior

Expect the password to get into RTL to be what we updated it to, but it's still the old password.

### Steps to Reproduce

Go to Services -> RTL -> Config and change the password.  Click save.

Now try to login to the RTL UI with the new password.  You cannot.

**Comment by chrisguida** [comment]
Fixed by https://github.com/Start9Labs/ride-the-lightning-wrapper/pull/32
