### ISSUE TITLE
[feat]: boltz-lnd service integration with lnd

### ISSUE THREAD

**Issue by LeoSpyke** [Start9Labs/ride-the-lightning-wrapper#38]
### Prerequisites

- [X] I have searched for existing issues that already suggest this feature.

### Describe the Feature Request

It would be great to have the integration with boltz-lnd client from the RTL web interface.

### Describe the Use Case

The main use case is to perform submarine and reverse submarine swaps.

### Describe Preferred Solution

The service can be enabled by default.

### Describe Alternatives

Another implementation is the service loopd by lightning labs (but it is already present inside the Lightning Terminal).

**Comment by Ciugam** [comment]
I think this could help the user to manage liquidity without opening other web pages and exposing to possible IP leak. 
I totally agree with this feature implementation, I hope it can be added soon.

**Comment by Dominion5254** [comment]
If I am understanding the boltz client works correctly, it seems boltz-lnd is not a feature to be exposed in RTL or even LND, but rather a separate service that would need to be packaged for StartOS to run alongside LND.

https://github.com/BoltzExchange/boltz-client

Closing as this is a request for a new service to be packaged, not an issue or feature to be added to this repo.
