### ISSUE TITLE
add camera functionality to RTL and thunderhub[feat]: 

### ISSUE THREAD

**Issue by OrangeGrasshopper** [Start9Labs/ride-the-lightning-wrapper#40]
### Prerequisites

- [X] I have searched for existing issues that already suggest this feature.

### Describe the Feature Request

I'd like both ride the lightning and thunderhub apps to include camera functionality making it easier to import mobile created lightning invoices.

### Describe the Use Case

It seems that importing an invoice created from a mobile wallet is not possible from within both ride the lightning and thunderhub apps. I'm forced to use another app to read the QR code then copy and paste it into the required field. 
The process should be simpler, right?

When clicking on the send lightning button an invoice field opens up. Shorten it a bit and place the camera icon next to it. Clicking within each area either opens the invoice box to full size allowing a paste operation or the camera activates capturing the QR code and inputs it into the invoice box.

### Describe Preferred Solution

This functionality exists in the versions on umbrel but not start9, so surely it can be done. 
Thanks

**Comment by Dominion5254** [comment]
While RTL can generate QR codes for invoices, scanning QR codes is not a feature currently supported by RTL.

Closing this issue as the feature you are describing would require upstream changes to RTL and there is an issue for that [here](https://github.com/Ride-The-Lightning/RTL/issues/1105).
