### ISSUE TITLE
[feat]:  Update to 14.1 due to LND taproot chan. (v0.17)

### ISSUE THREAD

**Issue by Ciugam** [Start9Labs/ride-the-lightning-wrapper#42]
### Prerequisites

- [X] I have searched for existing issues that already suggest this feature.

### Describe the Feature Request

Hi,
I want to request an update of RTL; 
2-week-old (from today) official release of RTL  (v14.1) supports opening Taproot Channels, so I think is important to update, and I hope it can be released asap.
Thanks in advance.

### Describe the Use Case

LND v0.17 got official support to Taproot Channels, which improve a lot privacy on the private channel side.
I think this feature is crucial since normal user in major cases would open private channels to send and receive his own sats without becoming a routing node.

**Comment by Dominion5254** [comment]
Closed by #43 

However, please note LL has indicated taproot channels are "[still experimental](https://lightning.engineering/posts/2023-10-03-lnd-0.17-launch/)" and has recommended "users first experiment with it [taproot channels] on testnet/regtest".
