### ISSUE TITLE
ride-the-lightning for 0.3.0

### ISSUE THREAD

**Issue by ProofOfKeags** [Start9Labs/ride-the-lightning-wrapper#9]
update to new package format for 0.3.0

- [ ] backup create
- [ ] backup restore
- [ ] configure
- [ ] actions
- [ ] health checks
- [ ] dependency configure
- [ ] start
- [ ] stop

**Comment by kn0wmad** [comment]
Is it in scope to add c-lightning support?

**Comment by chrisguida** [comment]
@kn0wmad could be a p2
